export default {
  SET_LOADING: "SET_LOADING",
  SET_FAILED: "SET_FAILED",
  FETCHING_REQUESTS: "FETCHING_REQUESTS",
  ADD_REQUEST: "ADD_REQUEST",
  MARK_REQUEST_AS_DONE: "MARK_REQUEST_AS_DONE",
  CLOSE_REQUEST: "CLOSE_REQUEST"
};
